# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  - Name: Orderer
    Domain: orderers.dlwan.phd
    EnableNodeOUs: true

    Specs:
      - Hostname: orderer1
        SANS:
          - orderer1.orderers.dlwan.phd
      - Hostname: orderer2
        SANS:
          - orderer2.orderers.dlwan.phd
      - Hostname: orderer3
        SANS:
          - orderer3.orderers.dlwan.phd
      - Hostname: orderer4
        SANS:
          - orderer4.orderers.dlwan.phd
      - Hostname: orderer5
        SANS:
      #    - orderer5.orderers.dlwan.phd
      #- Hostname: orderer6
      #  SANS:
      #    - orderer6.orderers.dlwan.phd
      #- Hostname: orderer7
      #  SANS:
      #    - orderer7.orderers.dlwan.phd
      #- Hostname: orderer8
      #  SANS:
      #    - orderer8.orderers.dlwan.phd
      #- Hostname: orderer9
      #  SANS:
      #    - orderer9.orderers.dlwan.phd
      #- Hostname: orderer10
      #  SANS:
      #    - orderer10.orderers.dlwan.phd
      #- Hostname: orderer11
      #  SANS:
      #    - orderer11.orderers.dlwan.phd
      #- Hostname: orderer12
      #  SANS:
      #    - orderer12.orderers.dlwan.phd
      #- Hostname: orderer13
      #  SANS:
      #    - orderer13.orderers.dlwan.phd
      #- Hostname: orderer14
      #  SANS:
      #    - orderer14.orderers.dlwan.phd
      #- Hostname: orderer15
      #  SANS:
      #    - orderer15.orderers.dlwan.phd
      #- Hostname: orderer16
      #  SANS:
      #    - orderer16.orderers.dlwan.phd

# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  - Name: Org1
    Domain: org1.dlwan.phd
    EnableNodeOUs: true
    Specs:
      - Hostname: peer0
        SANS:
          - peer0.org1.dlwan.phd
      - Hostname: peer1
        SANS:
          - peer1.org1.dlwan.phd
      - Hostname: peer2
        SANS:
          - peer2.org1.dlwan.phd
      - Hostname: peer3
        SANS:
          - peer3.org1.dlwan.phd
      - Hostname: peer4
      #  SANS:
      #    - peer4.org1.dlwan.phd
      #- Hostname: peer5
      #  SANS:
      #    - peer5.org1.dlwan.phd
      #- Hostname: peer6
      #  SANS:
      #    - peer6.org1.dlwan.phd
      #- Hostname: peer7
      #  SANS:
      #    - peer7.org1.dlwan.phd
      #- Hostname: peer8
      #  SANS:
      #    - peer8.org1.dlwan.phd
      #- Hostname: peer9
      #  SANS:
      #    - peer9.org1.dlwan.phd
      #- Hostname: peer10
      #  SANS:
      #    - peer10.org1.dlwan.phd
      #- Hostname: peer11
      #  SANS:
      #    - peer11.org1.dlwan.phd
      #- Hostname: peer12
      #  SANS:
      #    - peer12.org1.dlwan.phd
      #- Hostname: peer13
      #  SANS:
      #    - peer13.org1.dlwan.phd
      #- Hostname: peer14
      #  SANS:
      #    - peer14.org1.dlwan.phd
      #- Hostname: peer15
      #  SANS:
      #    - peer15.org1.dlwan.phd
    #Template:
    #  Count: 2
    #  SANS:
    Users:
      Count: 2

  #- Name: Org2
  #  Domain: org2.dlwan.phd
  #  EnableNodeOUs: true
  #  Specs:
  #    - Hostname: peer0
  #      SANS:
  #        - peer0.org2.dlwan.phd
  #    - Hostname: peer1
  #      SANS:
  #        - peer1.org2.dlwan.phd
  #    - Hostname: peer2
  #      SANS:
  #        - peer2.org2.dlwan.phd
  #    - Hostname: peer3
  #      SANS:
  #        - peer3.org2.dlwan.phd
  #    - Hostname: peer4
  #      SANS:
  #        - peer4.org2.dlwan.phd
  #    - Hostname: peer5
  #      SANS:
  #        - peer5.org2.dlwan.phd
  #    - Hostname: peer6
  #      SANS:
  #        - peer6.org2.dlwan.phd
  #    - Hostname: peer7
  #      SANS:
  #        - peer7.org2.dlwan.phd
  #    - Hostname: peer8
  #      SANS:
  #        - peer8.org2.dlwan.phd
  #    - Hostname: peer9
  #      SANS:
  #        - peer9.org2.dlwan.phd
  #    - Hostname: peer10
  #      SANS:
  #        - peer10.org2.dlwan.phd
  #    - Hostname: peer11
  #      SANS:
  #        - peer11.org2.dlwan.phd
  #    - Hostname: peer12
  #      SANS:
  #        - peer12.org2.dlwan.phd
  #    - Hostname: peer13
  #      SANS:
  #        - peer13.org2.dlwan.phd
  #    - Hostname: peer14
  #      SANS:
  #        - peer14.org2.dlwan.phd
  #    - Hostname: peer15
  #      SANS:
  #        - peer15.org2.dlwan.phd
  #  #Template:
  #  #  Count: 2
  #  #  SANS
  #  Users:
  #    Count: 2
  #
  #- Name: Org3
  #  Domain: org3.dlwan.phd
  #  EnableNodeOUs: true
  #  Specs:
  #    - Hostname: peer0
  #      SANS:
  #        - peer0.org3.dlwan.phd
  #    - Hostname: peer1
  #      SANS:
  #        - peer1.org3.dlwan.phd
  #    - Hostname: peer2
  #      SANS:
  #        - peer2.org3.dlwan.phd
  #    - Hostname: peer3
  #      SANS:
  #        - peer3.org3.dlwan.phd
  #    - Hostname: peer4
  #      SANS:
  #        - peer4.org3.dlwan.phd
  #    - Hostname: peer5
  #      SANS:
  #        - peer5.org3.dlwan.phd
  #    - Hostname: peer6
  #      SANS:
  #        - peer6.org3.dlwan.phd
  #    - Hostname: peer7
  #      SANS:
  #        - peer7.org3.dlwan.phd
  #    - Hostname: peer8
  #      SANS:
  #        - peer8.org3.dlwan.phd
  #    - Hostname: peer9
  #      SANS:
  #        - peer9.org3.dlwan.phd
  #    - Hostname: peer10
  #      SANS:
  #        - peer10.org3.dlwan.phd
  #    - Hostname: peer11
  #      SANS:
  #        - peer11.org3.dlwan.phd
  #    - Hostname: peer12
  #      SANS:
  #        - peer12.org3.dlwan.phd
  #    - Hostname: peer13
  #      SANS:
  #        - peer13.org3.dlwan.phd
  #    - Hostname: peer14
  #      SANS:
  #        - peer14.org3.dlwan.phd
  #    - Hostname: peer15
  #      SANS:
  #        - peer15.org3.dlwan.phd
  #  #Template:
  #  #  Count: 2
  #  #  SANS
  #  Users:
  #    Count: 2
